language: node_js
node_js:
   - "0.10"
before_install:
  - npm install nodeunit
script: nodeunit test
deploy:
  provider: opsworks
  access-key-id: AKIAJSW4BH2YECIJGD7Q
  secret-access-key: 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
  app-id: ec7381cd-f4e3-4f26-aa97-34be0c26bdc3