sudo: false
language: node_js
node_js:
- '0.10'
before_install:
- npm install nodeunit
script: nodeunit test
deploy:
  provider: opsworks
  access-key-id: AKIAJHZZDBOAUR3YMQIA
  secret-access-key:
    secure: TiDkqE95K3HzpnERex7XnefTuXCa+pfQUf0CQ6hddhKe36nAFmM462MDGjXTYzd5DmGvLfi3ayBzkOpwbEOjuPU6q5xrxxsIYk8Vh8tD8QcTB+6P5W5SpNYBs0DaWDu/eiQyktCbjFL1sRt65HqXUSkE5Z9jACTP4oYudNhg0Oc=
  app-id: 3534e70b-96bb-4e68-8cb8-65ef84985080
